#ifndef CONSTANTS_H
#define CONSTANTS_H

const int EXPLORE_PHASE_UPDATE = -1;
const int EXPLORE_PHASE_NEW_PATH = 0;
const int EXPLORE_PHASE_LOOP = 1;
const int EXPLORE_PHASE_EXPLORE = 2;
const int EXPLORE_PHASE_EXPERIMENT_LEARN = 3;
const int EXPLORE_PHASE_EXPERIMENT_MEASURE = 4;

const int EXPLORE_PHASE_EXPERIMENT_BACKPROP_DONE = 4;

const int EXPLORE_TYPE_NONE = 0;
const int EXPLORE_TYPE_NEW_PATH = 1;
const int EXPLORE_TYPE_LOOP = 2;

#endif /* CONSTANTS_H */